Frontend.Tests/Models/Direction.cs
using Newtonsoft.Json;

namespace Frontend.Tests.Models
{
    public class Direction
    {
        [JsonProperty("instructions")]
        public string Instructions { get; set; }

        [JsonProperty("optional")]
        public bool Optional { get; set; }
    }
}

Frontend.Tests/Models/Image.cs
using Newtonsoft.Json;

namespace Frontend.Tests.Models
{
    public class Image
    {
        [JsonProperty("full")]
        public string Full { get; set; }

        [JsonProperty("medium")]
        public string Medium { get; set; }

        [JsonProperty("small")]
        public string Small { get; set; }
    }
}

Frontend.Tests/Models/Ingredient.cs
using Newtonsoft.Json;
using System.Collections.Generic;

namespace Frontend.Tests.Models
{
    public class Ingredient
    {
        [JsonProperty("uuid")]
        public string UUID { get; set; }

        [JsonProperty("amount")]
        public string Amount { get; set; }

        [JsonProperty("measurement")]
        public string Measurement { get; set; }

        [JsonProperty("name")]
        public string Name { get; set; }

        [JsonIgnore]
        public List<Special> Specials { get; set; } = new List<Special>();
    }
}

Frontend.Tests/Models/Recipe.cs
using Frontend.Tests.Formatter;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;

namespace Frontend.Tests.Models
{
    public class Recipe
    {
        [JsonProperty("uuid")]
        public string UUID { get; set; }

        [JsonProperty("title")]
        public string Title { get; set; }

        [JsonProperty("images")]
        public Image Images { get; set; }

        [JsonProperty("description")]
        public string Description { get; set; }

        [JsonProperty("servings")]
        public int Servings { get; set; }

        [JsonProperty("prepTime")]
        public int PrepTime { get; set; }

        [JsonProperty("cookTime")]
        public int CookTime { get; set; }

        [JsonProperty("postDate"), JsonConverter(typeof(CustomDateFormat))]
        public DateTime PostDate { get; set; }

        [JsonProperty("editDate"), JsonConverter(typeof(CustomDateFormat))]
        public DateTime EditDate { get; set; }

        [JsonProperty("ingredients")]
        public List<Ingredient> Ingredients { get; set; }

        [JsonProperty("directions")]
        public List<Direction> Directions { get; set; }
    }
}

Frontend.Tests/Models/Special.cs
using Newtonsoft.Json;

namespace Frontend.Tests.Models
{
    public class Special
    {
        [JsonProperty("uuid")]
        public string UUID { get; set; }

        [JsonProperty("ingredientId")]
        public string IngredientId { get; set; }

        [JsonProperty("type")]
        public string Type { get; set; }

        [JsonProperty("title")]
        public string Title { get; set; }

        [JsonProperty("geo")]
        public string Geo { get; set; }

        [JsonProperty("text")]
        public string Text { get; set; }
    }
}

Frontend.Tests/Controllers/CrescendoController.cs
using Frontend.Tests.Models;
using Frontend.Tests.Service;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web;
using System.Web.Mvc;

namespace Frontend.Tests.Controllers
{
    public class CrescendoController : Controller
    {
        // GET: Crescendo
        public ActionResult Index()
        {
            //use dependency injection
            var recipeService = new RecipeService<Recipe>();

            var recipes = recipeService.GetAllRecipes();

            return View(recipes);
        }

        // GET: Crescendo/Details?recipeId
        public ActionResult Details(string recipeId)
        {
            //use dependency injection
            var recipeService = new RecipeService<Recipe>();

            var recipe = recipeService.GetRecipe(recipeId);

            return View(recipe);
        }

        public ActionResult Add()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Add(Recipe recipe)
        {
            if (recipe != null)
            {
                //use dependency injection
                var recipeService = new RecipeService<Recipe>();

                recipe.UUID = Guid.NewGuid().ToString();

                recipeService.AddRecipe(recipe);
            }

            return View();
        }

        [HttpGet]
        public ActionResult Update(string recipeId)
        {
            //use dependency injection
            var recipeService = new RecipeService<Recipe>();

            var recipe = recipeService.GetRecipe(recipeId);

            return View(recipe);
        }

        [HttpPost]
        public ActionResult Update(Recipe recipe)
        {
            //use dependency injection
            var recipeService = new RecipeService<Recipe>();

            bool isSuccess = recipeService.UpdateRecipe(recipe);

            if (isSuccess)
            {
                return RedirectToAction("Details", new { recipeId = recipe.UUID });
            }

            return View(recipe);
        }

        public ActionResult Special()
        {
            return View();
        }

        public ActionResult UpdateSpecial()
        {
            //use dependency injection
            var specialService = new SpecialService<Special>();

            var specials = specialService.GetAllSpecials();

            return View(specials);
        }

        [HttpPost]
        public ActionResult UpdateSpecial(Special special)
        {
            //use dependency injection
            var specialService = new SpecialService<Special>();

            bool isSuccess = specialService.UpdateSpecialItem(special);

            if (!isSuccess)
            {
                //log here
            }

            return RedirectToAction("UpdateSpecial");
        }

        // POST: Crescendo/Delete?recipeId
        public ActionResult Delete(string recipeId)
        {
            if (!string.IsNullOrEmpty(recipeId))
            {
                //use dependency injection
                var recipeService = new RecipeService<Recipe>();

                recipeService.DeleteRecipe(recipeId);
            }

            return RedirectToAction("Index");
        }

        [HttpGet]
        public JsonResult GetAllIngredients()
        {
            //use dependency injection
            var recipeService = new RecipeService<Recipe>();

            var recipes = recipeService.GetAllRecipes();

            return Json(recipes, JsonRequestBehavior.AllowGet);
        }

        public static List<Special> GetSpecialIngredient(string ingredientId)
        {
            //use dependency injection
            var specialService = new SpecialService<Special>();

            return specialService.GetSpecialIngredient(ingredientId);
        }

        [HttpGet]
        public JsonResult GetSpecialItem(string id)
        {
            //use dependency injection
            var specialService = new SpecialService<Special>();

            var specialItem = specialService.GetSpecialItem(id);

            return Json(specialItem, JsonRequestBehavior.AllowGet);
        }
    }
}

Frontend.Tests/Views/Crescendo/Add.cshtml
@using Frontend.Tests.Models
@model Recipe

<div class="row">
    @using (Html.BeginForm("Add", "Crescendo", FormMethod.Post))
    {
        <h2>Add Recipe</h2>
        <div class="row">
            <div class="form-group col-3">
                @Html.Label("Title", new { @class = "col-form-label" })
                @Html.TextBoxFor(model => model.Title, new { @class = "form-control", placeholder = "Title" })
            </div>
            <div class="form-group col-3">
                @Html.Label("Servings", new { @class = "col-form-label" })
                @Html.TextBoxFor(model => model.Servings, new { @class = "form-control", placeholder = "Servings" })
            </div>
            <div class="form-group col-3">
                @Html.Label("Preparation Time", new { @class = "col-form-label" })
                @Html.TextBoxFor(model => model.PrepTime, new { @class = "form-control", placeholder = "Preparation Time" })
            </div>
            <div class="form-group col-3">
                @Html.Label("Cooking Time", new { @class = "col-form-label" })
                @Html.TextBoxFor(model => model.CookTime, new { @class = "form-control", placeholder = "Cooking Time" })
            </div>
        </div>
        <div class="row">
            <div class="form-group col-6">
                @Html.Label("Description", new { @class = "col-form-label" })
                @Html.TextBoxFor(model => model.Description, new { @class = "form-control", placeholder = "Description" })
            </div>
        </div>
        <div class="row mt-3">
            <div class="form-group col-6">
                <button type="button" class="btn btn-outline-dark col-4">Add Ingredients</button>
            </div>
        </div>
        @Html.HiddenFor(model => model.PostDate, new { Value = DateTime.Now })
        @Html.HiddenFor(model => model.EditDate, new { Value = DateTime.Now })
        <div class="row mt-5">
            <div class="form-group col-6">
                <button type="submit" class="btn btn-outline-success col-6">Submit</button>
            </div>
        </div>

    }
</div>

Frontend.Tests/Views/Crescendo/Details.cshtml
@using Frontend.Tests.Models
@using Frontend.Tests.Controllers
@model Recipe

@if (Model != null)
{
    <div class="row">
        <h2>@Model.Title</h2>
        <h6>@Model.Description</h6>
        @if (Model.Images != null)
        {
            <img src="@Model.Images.Full" class="img-responsive img-thumbnail" />
        }
    </div>
    <div class="row">
        <div class="col-6">
            <p>Servings: @Model.Servings</p>
        </div>
        <div class="col-6">
            <p>Post Date: @Model.PostDate</p>
        </div>
    </div>
    <div class="row">
        <div class="col-6">
            <p>Preparation Time: @Model.PrepTime</p>
        </div>
        <div class="col-6">
            <p>Edit Date: @Model.EditDate</p>
        </div>
    </div>
    <div class="row">
        <p>Cook Time: @Model.CookTime</p>
    </div>
    <div class="row">
        <h4>Ingredients</h4>
        @if (Model.Ingredients != null)
        {
            <div class="table-responsive">
                <table class="table">
                    <thead>
                        <tr>
                            <th>Name</th>
                            <th>Amount</th>
                            <th>Measurement</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var ingredient in Model.Ingredients)
                        {
                            var specials = CrescendoController.GetSpecialIngredient(ingredient.UUID);

                            <tr>
                                <td class="col-6">
                                    <p class="fw-bold">@ingredient.Name</p>
                                    @if (specials?.Count > 0)
                                    {
                                        <div class="row m-1">
                                            <h6>Specials</h6>
                                            @foreach (var special in specials)
                                            {
                                                <p>Title: @special.Title</p>
                                                <p>Type: @special.Type</p>
                                                <p>Text: @special.Text</p>
                                            }
                                        </div>
                                    }

                                </td>

                                <td class="col-2">@ingredient.Amount</td>
                                <td class="col-4">@ingredient.Measurement</td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        }
    </div>
    <h4>Directions</h4>

    if (Model.Directions != null)
    {
        <div class="table-responsive">
            <table class="table">
                <thead>
                    <tr>
                        <th>Optional</th>
                        <th>Instructions</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var direction in Model.Directions)
                    {
                        string optionalText = direction.Optional ? "YES" : "NO";
                        <tr>
                            <td class="col-1">@optionalText</td>
                            <td class="col-11">@direction.Instructions</td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    }
}
else
{
    <p>No data available</p>
}

Frontend.Tests/Views/Crescendo/Index.cshtml
@using Frontend.Tests.Models
@model List<Recipe>

@{
    int counter = 0;
}

@helper AddRecipeItems(Recipe recipe)
{
    <div class="col-4 img-thumbnail">
        <a href="@Url.Action("Details", "Crescendo", new { recipeId = recipe.UUID })">
            @if (recipe.Images != null)
            {
                <img src="@recipe.Images.Small" class="img-responsive img-rounded" />
            }
            <h2>@recipe.Title</h2>
            <h6>@recipe.Description</h6>
        </a>
        <div class="row">
            <div class="col-6">
                @Html.ActionLink("Update", "Update", "Crescendo", new { recipeId = recipe.UUID }, new { @class = "btn btn-outline-success" })
            </div>
            <div class="col-6">
                @Html.ActionLink("Delete", "Delete", "Crescendo", new { recipeId = recipe.UUID }, new { @class = "btn btn-outline-danger" })
            </div>
        </div>
    </div>
}

@if (Model != null)
{
    foreach (var recipe in Model)
    {

        if (counter % 3 == 0)
        {
            @:<div class="row text-center">
                @AddRecipeItems(recipe)
            }
            else
            {
                @AddRecipeItems(recipe)
            }
            counter++;
            if (counter % 3 == 0 || recipe == Model.Last())
            {
            @:</div>
        }
    }
}

Frontend.Tests/Views/Crescendo/Special.cshtml
@using Frontend.Tests.Models
@model Special

<script type="text/javascript">
    function AssociateToIngredient() {

        $.getJSON("/Crescendo/GetAllIngredients", function (data) {
            console.log(data);
        })
    }

</script>

<div class="row">
    @using (Html.BeginForm("Special", "Crescendo", FormMethod.Post))
    {
        <h2>Add Special</h2>
        <div class="row col-6">
            <div class="form-group col-6">
                @Html.Label("Title", new { @class = "col-form-label" })
                @Html.TextBox("Title", "", new { @class = "form-control", placeholder = "Title" })
            </div>
            <div class="form-group col-6">
                @Html.Label("Type", new { @class = "col-form-label" })
                @Html.TextBox("Type", "", new { @class = "form-control", placeholder = "Type" })
            </div>
        </div>
        <div class="row col-6">
            <div class="form-group col-6">
                @Html.Label("Geo", new { @class = "col-form-label" })
                @Html.TextBox("Geo", "", new { @class = "form-control", placeholder = "Geo" })
            </div>
            <div class="form-group col-6">
                @Html.Label("Text", new { @class = "col-form-label" })
                @Html.TextBox("Text", "", new { @class = "form-control", placeholder = "Text" })
            </div>
        </div>
        <div class="row mt-3">
            <div class="form-group col-6">
                <button type="button" class="btn btn-outline-dark col-4" onclick="AssociateToIngredient()">Associate to Ingredient</button>
            </div>
        </div>
        <div class="row mt-5">
            <div class="form-group col-6">
                <button type="submit" class="btn btn-outline-success col-6">Submit</button>
            </div>
        </div>
    }
</div>

Frontend.Tests/Views/Crescendo/Update.cshtml
@using Frontend.Tests.Models
@using Frontend.Tests.Controllers

@model Recipe

@if (Model != null)
{
    using (Html.BeginForm("Update", "Crescendo", FormMethod.Post))
    {
        <h2>Updating Recipe Id: @Model.UUID</h2>
        <div class="row">
            <div class="form-group col-3">
                @Html.Label("Title", new { @class = "col-form-label" })
                @Html.TextBoxFor(model => model.Title, new { @class = "form-control", placeholder = "Title" })
            </div>
            <div class="form-group col-3">
                @Html.Label("Servings", new { @class = "col-form-label" })
                @Html.TextBoxFor(model => model.Servings, new { @class = "form-control", placeholder = "Servings" })
            </div>
            <div class="form-group col-3">
                @Html.Label("Preparation Time", new { @class = "col-form-label" })
                @Html.TextBoxFor(model => model.PrepTime, new { @class = "form-control", placeholder = "Preparation Time" })
            </div>
            <div class="form-group col-3">
                @Html.Label("Cooking Time", new { @class = "col-form-label" })
                @Html.TextBoxFor(model => model.CookTime, new { @class = "form-control", placeholder = "Cooking Time" })
            </div>
        </div>
        <div class="row">
            <div class="form-group col-6">
                @Html.Label("Description", new { @class = "col-form-label" })
                @Html.TextBoxFor(model => model.Description, new { @class = "form-control", placeholder = "Description" })
            </div>
        </div>
        <div class="row">
            @if (Model.Images != null)
            {
                <img src="@Model.Images.Full" class="img-responsive img-thumbnail " />
                @Html.HiddenFor(model => model.Images.Full)
                @Html.HiddenFor(model => model.Images.Medium)
                @Html.HiddenFor(model => model.Images.Small)
            }
        </div>
        <div class="row">
            <h4>Ingredients</h4>
            @if (Model.Ingredients != null)
            {
                <div class="table-responsive">
                    <table class="table">
                        <thead>
                            <tr>
                                <th>Name</th>
                                <th>Amount</th>
                                <th>Measurement</th>
                            </tr>
                        </thead>
                        <tbody>
                            @for (int counter = 0; counter < Model.Ingredients.Count; counter++)
                            {
                                <tr>
                                    @Html.HiddenFor(model => model.Ingredients[counter].UUID)
                                    <td class="col-6">
                                        @Html.TextBoxFor(model => model.Ingredients[counter].Name, new { @class = "form-control", placeholder = "Ingredient Name" })
                                    </td>

                                    <td class="col-2">
                                        @Html.TextBoxFor(model => model.Ingredients[counter].Amount, new { @class = "form-control", placeholder = "Amount" })
                                    </td>
                                    <td class="col-4">
                                        @Html.TextBoxFor(model => model.Ingredients[counter].Measurement, new { @class = "form-control", placeholder = "Measurement" })
                                    </td>
                                </tr>

                            }
                        </tbody>
                    </table>
                </div>
            }
        </div>
        <h4>Directions</h4>

        if (Model.Directions != null)
        {
            <div class="table-responsive">
                <table class="table">
                    <thead>
                        <tr>
                            <th>Optional</th>
                            <th>Instructions</th>
                        </tr>
                    </thead>
                    <tbody>
                        @for (int counter = 0; counter < Model.Directions.Count; counter++)
                        {
                            string optionalText = Model.Directions[counter].Optional ? "YES" : "NO";
                            <tr>
                                <td class="col-1">
                                    @Html.CheckBoxFor(model => model.Directions[counter].Optional, new { @class = "form-check-input" })
                                </td>
                                <td class="col-11">
                                    @Html.TextBoxFor(model => model.Directions[counter].Instructions, new { @class = "form-control", placeholder = "Instructions" })
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
            @Html.HiddenFor(model => model.UUID)
            @Html.HiddenFor(model => model.EditDate, new { Value = DateTime.Now })
            @Html.HiddenFor(model => model.PostDate, new { Value = DateTime.Now })
            <button type="submit" class="btn btn-outline-success col-4">Update</button>
        }
    }
}
else
{
    <p> No data available</p>
}

Frontend.Tests/Views/Crescendo/UpdateSpecial.cshtml
@using Frontend.Tests.Models
@using Frontend.Tests.Controllers

@model List<Special>

<script type="text/javascript">
    $(function () {
        $('#update-special').hide();

        $('#uuid-dropdown').on('change', function () {

            $.getJSON("/Crescendo/GetSpecialItem/" + this.value, function (data) {

                $('[name=IngredientId]').val(data.IngredientId);
                $('[name=Title]').val(data.Title);
                $('[name=Type]').val(data.Type);
                $('[name=Geo]').val(data.Geo);
                $('[name=Text]').val(data.Text);
                $('#update-special').show();

            });

        });
    });   
</script>

@if (Model?.Count > 0)
{
    <div class="row">
        @using (Html.BeginForm("UpdateSpecial", "Crescendo", FormMethod.Post))
        {
            <h2>Update Special</h2>

            <div class="row col-6">
                <div class="form-group col-6">
                    @Html.Label("UUID", new { @class = "col-form-label" })
                    @Html.DropDownList("UUID", new SelectList(Model.Select(s => s.UUID)), "Please Select", new { @class = "form-control", @id = "uuid-dropdown" })
                    @Html.Hidden("IngredientId")
                </div>
            </div>
            <div id="update-special">
                <div class="row col-6">
                    <div class="form-group col-6">
                        @Html.Label("Title", new { @class = "col-form-label" })
                        @Html.TextBox("Title", "", new { @class = "form-control", placeholder = "Title" })
                    </div>
                    <div class="form-group col-6">
                        @Html.Label("Type", new { @class = "col-form-label" })
                        @Html.TextBox("Type", "", new { @class = "form-control", placeholder = "Type" })
                    </div>
                </div>
                <div class="row col-6">
                    <div class="form-group col-6">
                        @Html.Label("Geo", new { @class = "col-form-label" })
                        @Html.TextBox("Geo", "", new { @class = "form-control", placeholder = "Geo" })
                    </div>
                    <div class="form-group col-6">
                        @Html.Label("Text", new { @class = "col-form-label" })
                        @Html.TextBox("Text", "", new { @class = "form-control", placeholder = "Text" })
                    </div>
                </div>
                <div class="row mt-5">
                    <div class="form-group col-6">
                        <button type="submit" class="btn btn-outline-success col-6">Update</button>
                    </div>
                </div>
            </div>
        }
    </div>
}
else
{
    <p>No data available.</p>
}

Frontend.Tests/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.8.3.js"></script>
    <script src="~/Scripts/jquery-3.4.1.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="row col-8">
                @Html.ActionLink("Home", "Index", "Crescendo", new { area = "" }, new { @class = "btn btn-outline-primary col-3" })
                @Html.ActionLink("Add Recipe", "Add", "Crescendo", new { area = "" }, new { @class = "btn btn-outline-secondary col-3" })
                @Html.ActionLink("Add Special", "Special", "Crescendo", new { area = "" }, new { @class = "btn btn-outline-secondary col-3" })
                @Html.ActionLink("Update Special", "UpdateSpecial", "Crescendo", new { area = "" }, new { @class = "btn btn-outline-secondary col-3" })
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2021 - My ASP.NET Application</p>
        </footer>
    </div>
</body>
</html>